repos:
-   repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version
    hooks:
    -   id: black
        args: [., --config=./pyproject.toml]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.0  # Use the latest stable version
    hooks:
    -   id: isort
        args: [--settings-file=./pyproject.toml, --profile=black]

-   repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Use the latest stable version
    hooks:
    -   id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0  # Use the latest stable version
    hooks:
    -   id: mypy
        args: [--config-file=./pyproject.toml, --ignore-missing-imports]