name: Lint

on:
  push:
    branches:
      - '**'  # This will match all branches

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 mypy Flake8-pyproject
          
      - name: Lint with flake8
        run: flake8 . --config=./pyproject.toml --count --max-line-length=100 --statistics
        
      - name: Type check with mypy
        run: mypy . --config=./pyproject.toml --ignore-missing-imports 