name: Test

on:
  push:
    branches:
      - '**'  # This will match all branches
  pull_request:
    branches:
      - '**'  # This will match all branches

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov bcrypt
          pip install -e .
          
      - name: Run tests with pytest
        run: |
          pytest tests/ --cov=./ --cov-report=html
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.html
          fail_ci_if_error: true 